
#FROM will define the base image
FROM python:3.9

#RUN will be executing shell commands inside this containers asi its run in it
RUN pip install --no-cache-dir boto3

#CMD will by run every time you lunch a new container from the image, or when you restart a stopped container
CMD "python:3.9.11"

